# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               gfrison
tagline:             ''
description:         'Made by <a href="https://twitter.com/gfrison" target="_blank">@gfrison</a>.'
url:                 'https://gfrison.com'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              'Giancarlo F'
  url:               'https://twitter.com/gfrison'

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
