# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Giancarlo Frison
tagline:             'Signals from the Noise'
description:         'Made by <a href="https://twitter.com/gfrison" target="_blank">@gfrison</a>. Munich, Germany'
url:                 'https://gfrison.com'
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              'Giancarlo Frison'
  url:               'https://twitter.com/gfrison'
  twitter: gfrison
twitter:
  username: gfrison
social:
  title: Signals from the Noise
  name: Giancarlo Frison
  links:
    - https://twitter.com/gfrison
    - https://www.linkedin.com/in/gfrison
    - https://github.com/gfrison
    - https://keybase.io/gfrison
    - https://www.flickr.com/photos/gfrison/
# Custom vars
version:             1.0.0

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
